"use client";

import Link from "next/link";
import { Bell, ChevronDown, Menu, Search, Users } from "lucide-react";

export function WorkspaceHeader({ projectId, project, onMenu }: { projectId: string; project: { name: string; project_type: string; visibility: string; updated_at: string }; onMenu: () => void }) {
  const updated = new Intl.DateTimeFormat("en", { month: "short", day: "numeric" }).format(new Date(project.updated_at));
  return <header className="border-b border-border pb-5"><div className="flex items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><button className="rounded-md border border-border p-2 text-text-muted hover:bg-surface hover:text-text-primary lg:hidden" aria-label="Open workspace navigation" onClick={onMenu}><Menu className="h-5 w-5" /></button><Link href="/dashboard" className="hidden text-sm text-text-muted hover:text-text-primary sm:inline">Projects</Link><span className="hidden text-text-muted sm:inline">/</span><div className="min-w-0"><p className="truncate font-heading text-lg font-semibold text-text-primary">{project.name}</p><p className="font-mono text-[10px] uppercase tracking-[0.12em] text-text-muted">{project.project_type} · {project.visibility === "private" ? "Private" : "Published"}</p></div></div><div className="flex items-center gap-1"><button className="hidden rounded-md p-2 text-text-muted hover:bg-surface hover:text-text-primary sm:block" aria-label="Search workspace"><Search className="h-4 w-4" /></button><button className="rounded-md p-2 text-text-muted hover:bg-surface hover:text-text-primary" aria-label="Notifications coming soon"><Bell className="h-4 w-4" /></button><Link href={`/project/${projectId}/team`} className="hidden min-h-10 items-center gap-2 rounded-md border border-border px-3 text-sm font-medium text-text-primary hover:border-secondary hover:text-secondary sm:inline-flex"><Users className="h-4 w-4" />Invite</Link><button className="rounded-md p-2 text-text-muted hover:bg-surface hover:text-text-primary" aria-label="Open user menu"><ChevronDown className="h-4 w-4" /></button></div></div><div className="mt-4 flex items-center justify-between text-xs text-text-muted"><span>Last updated {updated}</span><span className="font-mono uppercase tracking-[0.1em]">Workspace / active</span></div></header>;
}
