"use client";

import Link from "next/link";
import { ArrowRight, BookOpen, Check, ChevronDown, Clock3, FileText, Flag, MoreHorizontal, Plus, Users } from "lucide-react";
import type { WorkspaceOverviewData } from "./data";

export function WorkspaceOverview({ projectId, data }: { projectId: string; data: WorkspaceOverviewData }) {
  return <div className="grid gap-8 xl:grid-cols-[minmax(0,1fr)_280px]">
    <div className="min-w-0">
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-mono text-xs uppercase tracking-[0.14em] text-secondary">Overview / project studio</p><h2 className="mt-2 font-heading text-3xl font-semibold tracking-tight text-text-primary">Keep the build moving.</h2><p className="mt-2 max-w-xl text-text-muted">A clear view of what changed, what is next, and where the record needs attention.</p></div><Link href={`/project/${projectId}/docs`} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white hover:bg-primary-hover"><BookOpen className="h-4 w-4" aria-hidden />Continue documenting</Link></div>
      <div className="mt-8 grid gap-px overflow-hidden border border-border bg-border sm:grid-cols-3"><SummaryMetric label="Completeness" value={`${data.stats.completeness}%`} detail="documented and reviewed" /><SummaryMetric label="Active milestone" value="01" detail={data.stats.activeMilestone} /><SummaryMetric label="Recent updates" value={data.stats.recentUpdates} detail="across the workspace" /></div>
      <div className="mt-8 grid gap-8 lg:grid-cols-[1.1fr_.9fr]">
        <section className="border-t border-border pt-5"><SectionHeader title="Project health" action="View activity" /><div className="mt-5 grid gap-4 rounded-lg border border-border bg-surface p-5"><div className="flex items-end justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[0.12em] text-text-muted">Documentation completeness</p><p className="mt-2 font-heading text-4xl font-semibold text-text-primary">{data.stats.completeness}<span className="text-lg text-text-muted">%</span></p></div><span className="rounded-full border border-warning-border bg-warning-bg px-2 py-1 text-xs text-warning">Testing phase</span></div><div className="h-2 overflow-hidden rounded-full bg-input-bg" role="progressbar" aria-label="Documentation completeness" aria-valuenow={data.stats.completeness} aria-valuemin={0} aria-valuemax={100}><div className="h-full rounded-full bg-secondary transition-[width] duration-500" style={{ width: `${data.stats.completeness}%` }} /></div><div className="grid grid-cols-2 gap-4 border-t border-border pt-4 text-sm"><div><p className="text-text-muted">Tasks completed</p><strong className="text-text-primary">{data.stats.completedTasks}</strong></div><div><p className="text-text-muted">Next focus</p><strong className="text-text-primary">{data.stats.activeMilestone}</strong></div></div></div></section>
        <ActivityCard activity={data.activity} />
      </div>
      <div className="mt-8 grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><DocumentationCard projectId={projectId} documents={data.documents} /><MilestonesCard milestones={data.milestones} /></div>
      <div className="mt-8 grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><TeamCard members={data.team} /><QuickActions projectId={projectId} /></div>
    </div>
    <ContextPanel projectId={projectId} data={data} />
  </div>;
}

function SummaryMetric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="bg-surface p-5"><p className="font-mono text-[10px] uppercase tracking-[0.12em] text-text-muted">{label}</p><p className="mt-4 font-heading text-2xl font-semibold text-text-primary">{value}</p><p className="mt-1 text-xs text-text-muted">{detail}</p></div>; }
function SectionHeader({ title, action }: { title: string; action?: string }) { return <div className="flex items-center justify-between gap-4"><h3 className="font-heading text-lg font-semibold text-text-primary">{title}</h3>{action && <span className="text-sm text-secondary">{action}</span>}</div>; }
function ActivityCard({ activities }: Pick<WorkspaceOverviewData, "activity">) { return <section className="border-t border-border pt-5"><SectionHeader title="Recent activity" action="All activity" /><div className="mt-4 grid gap-4">{activities.map(({ id, icon: Icon, title, detail, time }) => <div key={id} className="flex gap-3"><span className="mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-full border border-border bg-surface"><Icon className="h-4 w-4 text-secondary" aria-hidden /></span><div className="min-w-0"><p className="text-sm font-medium text-text-primary">{title}</p><p className="mt-0.5 text-xs text-text-muted">{detail}</p></div><time className="ml-auto shrink-0 text-xs text-text-muted">{time}</time></div>)}</div></section>; }
function DocumentationCard({ projectId, documents }: { projectId: string; documents: WorkspaceOverviewData["documents"] }) { return <section className="border-t border-border pt-5"><SectionHeader title="Documentation" action="View all" /><div className="mt-4 grid gap-2">{documents.map((document) => <Link href={`/project/${projectId}/docs?document=${document.id}`} key={document.id} className="flex min-h-14 items-center gap-3 rounded-md border border-border px-3 py-3 transition-colors hover:bg-surface"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-md ${document.status === "reviewed" ? "bg-success-bg text-success" : "bg-warning-bg text-warning"}`}><FileText className="h-4 w-4" aria-hidden /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium text-text-primary">{document.title}</span><span className="block truncate text-xs text-text-muted">{document.owner} · updated {document.updated}</span></span><span className="text-xs text-text-muted">{document.status === "reviewed" ? "Reviewed" : "In progress"}</span></Link>)}</div></section>; }
function MilestonesCard({ milestones }: Pick<WorkspaceOverviewData, "milestones">) { return <section className="border-t border-border pt-5"><SectionHeader title="Milestones" action="View all" /><div className="mt-4 grid gap-4">{milestones.map((milestone) => <div className="flex gap-3" key={milestone.id}><span className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${milestone.status === "active" ? "bg-secondary" : "bg-border"}`} /><div className="min-w-0"><div className="flex justify-between gap-3"><p className="text-sm font-medium text-text-primary">{milestone.title}</p><time className="font-mono text-[10px] text-text-muted">{milestone.date}</time></div><p className="mt-1 text-xs leading-relaxed text-text-muted">{milestone.detail}</p></div></div>)}</div></section>; }
function TeamCard({ members }: Pick<WorkspaceOverviewData, "team">) { return <section className="border-t border-border pt-5"><SectionHeader title="Team snapshot" action="Manage team" /><div className="mt-4 grid gap-3">{members.map((member) => <div className="flex items-center gap-3" key={member.id}><span className={`grid h-8 w-8 place-items-center rounded-full text-xs font-medium text-white ${member.tone}`}>{member.initials}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium text-text-primary">{member.name}</span><span className="block text-xs text-text-muted">{member.role}</span></span><span className="h-2 w-2 rounded-full bg-success" aria-label="Active" /></div>)}</div></section>; }
function QuickActions({ projectId }: { projectId: string }) { return <section className="border-t border-border pt-5"><SectionHeader title="Quick actions" /><div className="mt-4 grid gap-2 sm:grid-cols-2"><Link href={`/project/${projectId}/docs`} className="flex min-h-11 items-center gap-2 rounded-md border border-border px-3 text-sm text-text-primary hover:bg-surface"><Plus className="h-4 w-4 text-secondary" />Create documentation</Link><span className="flex min-h-11 cursor-not-allowed items-center gap-2 rounded-md border border-border px-3 text-sm text-text-muted"><Flag className="h-4 w-4" />Add milestone <span className="ml-auto font-mono text-[9px]">SOON</span></span><span className="flex min-h-11 cursor-not-allowed items-center gap-2 rounded-md border border-border px-3 text-sm text-text-muted"><Users className="h-4 w-4" />Invite member <span className="ml-auto font-mono text-[9px]">SOON</span></span><span className="flex min-h-11 cursor-not-allowed items-center gap-2 rounded-md border border-border px-3 text-sm text-text-muted"><FolderOpenIcon />Upload files <span className="ml-auto font-mono text-[9px]">SOON</span></span></div></section>; }
function FolderOpenIcon() { return <span className="h-4 w-4 rounded-sm border border-current" aria-hidden />; }
function ContextPanel({ projectId, data }: { projectId: string; data: WorkspaceOverviewData }) { return <aside className="border-t border-border pt-5 xl:border-l xl:border-t-0 xl:pl-6"><div className="flex items-center justify-between"><p className="font-mono text-xs uppercase tracking-[0.14em] text-text-muted">Project context</p><button className="rounded-md p-2 text-text-muted hover:bg-surface hover:text-text-primary" aria-label="Collapse project context"><ChevronDown className="h-4 w-4" /></button></div><div className="mt-5 grid gap-6"><div><p className="text-xs text-text-muted">Objective</p><p className="mt-2 text-sm leading-relaxed text-text-primary">{data.project.objective}</p></div><div><p className="text-xs text-text-muted">Current phase</p><p className="mt-2 flex items-center gap-2 text-sm font-medium text-text-primary"><span className="h-2 w-2 rounded-full bg-warning" />{data.project.phase}</p></div><div><p className="text-xs text-text-muted">Category</p><p className="mt-2 text-sm text-text-primary">{data.project.category}</p></div><div><p className="text-xs text-text-muted">Tags</p><div className="mt-2 flex flex-wrap gap-1.5">{data.project.tags.map((tag) => <span className="rounded-full border border-border px-2 py-1 text-xs text-text-muted" key={tag}>{tag}</span>)}</div></div><div><p className="text-xs text-text-muted">Pinned resources</p><div className="mt-2 grid gap-2"><span className="flex items-center gap-2 text-sm text-text-primary"><FileText className="h-4 w-4 text-secondary" />Requirements notes</span><span className="flex items-center gap-2 text-sm text-text-primary"><FileText className="h-4 w-4 text-secondary" />Field test checklist</span></div></div><Link href={`/project/${projectId}/docs`} className="inline-flex items-center gap-2 text-sm font-medium text-secondary hover:underline">Open the record <ArrowRight className="h-4 w-4" /></Link></div></aside>; }
